### ISSUE TITLE
Some strange errors

### ISSUE THREAD

**Issue by YZWYD** [Lab-of-AI-and-Robotics/GS_ICP_SLAM#12]
First of all, I would like to thank the open source community for such excellent work! When I tried to replicate this work on Jetson AGX Orin, I encountered some errors.
(gsicpslam) nvidia@ubuntu:~/project/GS_ICP_SLAM-main$ bash tum_unlimit.sh
run rgbd_dataset_freiburg1_desk
Traceback (most recent call last):
  File "gs_icp_slam_unlimit.py", line 240, in <module>
    gs_icp_slam.run()
  File "gs_icp_slam_unlimit.py", line 119, in run
    p.start()
  File "/home/nvidia/anaconda3/envs/gsicpslam/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/nvidia/anaconda3/envs/gsicpslam/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/nvidia/anaconda3/envs/gsicpslam/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/home/nvidia/anaconda3/envs/gsicpslam/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/nvidia/anaconda3/envs/gsicpslam/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/nvidia/anaconda3/envs/gsicpslam/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/nvidia/anaconda3/envs/gsicpslam/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "/home/nvidia/anaconda3/envs/gsicpslam/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 270, in reduce_tensor
    event_sync_required) = storage._share_cuda_()
  File "/home/nvidia/anaconda3/envs/gsicpslam/lib/python3.8/site-packages/torch/storage.py", line 1034, in _share_cuda_
    return self._untyped_storage._share_cuda_(*args, **kwargs)
RuntimeError: CUDA error: operation not supported
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

run rgbd_dataset_freiburg2_xyz
Traceback (most recent call last):
  File "gs_icp_slam_unlimit.py", line 240, in <module>
    gs_icp_slam.run()
  File "gs_icp_slam_unlimit.py", line 119, in run
    p.start()
  File "/home/nvidia/anaconda3/envs/gsicpslam/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/nvidia/anaconda3/envs/gsicpslam/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/nvidia/anaconda3/envs/gsicpslam/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/home/nvidia/anaconda3/envs/gsicpslam/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/nvidia/anaconda3/envs/gsicpslam/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/nvidia/anaconda3/envs/gsicpslam/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/nvidia/anaconda3/envs/gsicpslam/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "/home/nvidia/anaconda3/envs/gsicpslam/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 270, in reduce_tensor
    event_sync_required) = storage._share_cuda_()
  File "/home/nvidia/anaconda3/envs/gsicpslam/lib/python3.8/site-packages/torch/storage.py", line 1034, in _share_cuda_
    return self._untyped_storage._share_cuda_(*args, **kwargs)
RuntimeError: CUDA error: operation not supported
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

run rgbd_dataset_freiburg3_long_office_household
Traceback (most recent call last):
  File "gs_icp_slam_unlimit.py", line 240, in <module>
    gs_icp_slam.run()
  File "gs_icp_slam_unlimit.py", line 119, in run
    p.start()
  File "/home/nvidia/anaconda3/envs/gsicpslam/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/nvidia/anaconda3/envs/gsicpslam/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/nvidia/anaconda3/envs/gsicpslam/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/home/nvidia/anaconda3/envs/gsicpslam/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/nvidia/anaconda3/envs/gsicpslam/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/nvidia/anaconda3/envs/gsicpslam/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/nvidia/anaconda3/envs/gsicpslam/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "/home/nvidia/anaconda3/envs/gsicpslam/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 270, in reduce_tensor
    event_sync_required) = storage._share_cuda_()
  File "/home/nvidia/anaconda3/envs/gsicpslam/lib/python3.8/site-packages/torch/storage.py", line 1034, in _share_cuda_
    return self._untyped_storage._share_cuda_(*args, **kwargs)
RuntimeError: CUDA error: operation not supported
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by Launch-on-Titania** [comment]
I meet this problem too. 
And I fixed by reinstalling fast_gicp, when u install fast_gicp, 
- u should got clone GS_ICP_SLAM in --recursive, 
- then after install pcl, uses gcc g++ 11.4 to compile fast_gicp(steps as shown in README)
Finally, it's done for me
